### ISSUE TITLE
Foundation with BoM_OpsManager_product_version commented out still attempts to apply globalPatchFiles

### ISSUE THREAD

**Issue by xyloman** [pivotalservices/pcf-pipelines-maestro#1]
Since we leverage openstack for our foundation pipeline we have the param BoM_OpsManager_product_version commented out in our foundation configuration on this iaas type.  This has worked until we recently synced with maestro project this morning which resulted in the following error:
```
cp: cannot stat './globalPatchFiles/upgrade-ops-manager/openstack/pipeline.yml': No such file or directory
```

**Comment by lsilvapvt** [comment]
Thanks for reporting this problem. 
A fix for it has been provided in commit https://github.com/pivotalservices/pcf-pipelines-maestro/commit/e5927678eb80622dbb2c4e8f522e067ccd54e5bb.
