### ISSUE TITLE
Ops manager upgrade pipeline creation failing missing required variable

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotalservices/pcf-pipelines-maestro#11]
Ops manager upgrade is failing due to missing variable

![image](https://user-images.githubusercontent.com/2275490/30224214-b85c1940-9482-11e7-81b4-374a26b8569d.png)

I have opened pull request

https://github.com/pivotalservices/pcf-pipelines-maestro/pull/10

to add the missing variable to the foundation template file.

**Comment by lsilvapvt** [comment]
Support for pcf-pipelines 0.16.0 added in https://github.com/pivotalservices/pcf-pipelines-maestro/commit/ae49f7154295532ee5bdd88374f4eff796310818
