### ISSUE TITLE
missing inputs: pipelines-upgrade-custom-tasks, tool-om

### ISSUE THREAD

**Issue by johnlonganecker** [pivotalservices/pcf-pipelines-maestro#13]
We are using 01c3cd56 and are running into this error message 

```
missing input: pipeline-upgrade-custom-tasks, tool-om
```

When trying to `apply changes` on our SCS tile (1.4.2 -> 1.4.4). It is in the `wait-opsman-clear-running-tasks` task

Any idea what might be causing this?

Thanks!

**Comment by lsilvapvt** [comment]
Please retry with https://github.com/pivotalservices/pcf-pipelines-maestro/releases/tag/v0.2.0 and `pcf-pipelines` `v0.16.0` . In Maestro v0.2.0, the `wait-opsman-clear-running-tasks` is not modified anymore by the `gated-Apply-Changes-Job` flag and should work as the original step delivered by that `pcf-pipelines` release.

**Comment by johnlonganecker** [comment]
I will give that a try later today and get back to you. Thanks for the quick response.

**Comment by johnlonganecker** [comment]
Yup that resolved the problem.
