### ISSUE TITLE
The upload-product folder was not found because pcf-pipelines renamed it

### ISSUE THREAD

**Issue by eamonryan** [pivotalservices/pcf-pipelines-maestro#15]
Using v0.2.1 Maestro with v0.17.0 pcf-pipelines all of the upload tile stages failed with this error:

`task config 'pcf-pipelines/tasks/upload-product/task.yml' not found`

Looking at https://github.com/pivotal-cf/pcf-pipelines/tree/v0.17.0/tasks we can see that there is no `upload-product` folder, only an `upload-product-and-stemcell` folder

It looks like the folder was probably renamed on pcf-pipelines and this needs to be accounted for at https://github.com/pivotalservices/pcf-pipelines-maestro/blob/master/operations/opsfiles/single-foundation-pipeline/single-pipeline-upgrade-tile.yml#L72

**Comment by gwhaight** [comment]
heya, after changing the folder parameter to "upload-product-and-stemcell" the error goes away but still fails in the same section.

![image](https://user-images.githubusercontent.com/31929251/31197373-83a9f070-a916-11e7-98e1-f7f6b9d9027c.png)

**Comment by eamonryan** [comment]
Clarifying - this is using the single pipeline configuration option.

**Comment by lsilvapvt** [comment]
Fixes for the single pipeline generation with pcf-pipelines 0.17.0 checked in with https://github.com/pivotalservices/pcf-pipelines-maestro/commit/78767a0720e8e4eb93215252e5ea6e81ae8d64d4.
