### ISSUE TITLE
ERT Upgrade Downloading PCF Small Footprint Runtime

### ISSUE THREAD

**Issue by johnlonganecker** [pivotalservices/pcf-pipelines-maestro#17]
It looks like it is this bug:
https://github.com/pivotal-cf/pcf-pipelines/issues/210

it claims the fix is in: pcf-pipelines release v0.21.1 but latest maestro uses pcf-pipelines v0.19.2

was this commit suppose to fix it?
https://github.com/pivotalservices/pcf-pipelines-maestro/commit/41a6e70aa249da50871c88be66ec627071269232

We pulled in the latest commits from maestro, but we are still getting this problem. Am I missing something? Thanks!

**Comment by lsilvapvt** [comment]
Thanks for reporting the issue @johnlonganecker. Pcf-pipelines v0.21.1 is now supported with commit https://github.com/pivotalservices/pcf-pipelines-maestro/commit/0b5723bdf1e1182617c79d24d24f575944c6a1d3
