### ISSUE TITLE
Pivnet to S3 Gated setup

### ISSUE THREAD

**Issue by johnlonganecker** [pivotalservices/pcf-pipelines-maestro#18]
Is there a way to have a sandbox environment that uses pivnet to download tiles then on successful upgrades it uploads that tile to s3 then a pre-prod environment grabs them from s3?

That way we can gate upgrades between foundations.

**Comment by lsilvapvt** [comment]
hi @johnlonganecker. Maestro itself does not yet provide a feature to populate a S3 bucket with release files to be consumed by the pcf-pipelines, but there is an example on how you can do so in the `pcf-pipelines` repo: https://github.com/pivotal-cf/pcf-pipelines/blob/master/docs/offline-pipelines.md 
You could use the sample `create-offline-pinned-pipelines` pipeline to populate your S3 repository. 
Then, you could try Maestro's S3 integration feature (https://github.com/pivotalservices/pcf-pipelines-maestro/blob/master/common/credentials.yml#L54) to consume the release files from S3. Just a heads up that such feature is still work-in-progress and experimental for Maestro and it may require some TLC to get it working with the latest versions of `pcf-pipelines`. If you go that route, issues+PRs are welcome. Thanks!
