### ISSUE TITLE
Get PCF-Pipelines from Pivnet or Github release

### ISSUE THREAD

**Issue by lenisha** [pivotalservices/pcf-pipelines-maestro#2]
Add Trigger regulator to Maesto Orchestrator and operations (patch) files to set a trigger based on
- Pivnet release
- Github  Release
- Git  ( for local testing or private enterprise git)

**Comment by lsilvapvt** [comment]
Commit https://github.com/pivotalservices/pcf-pipelines-maestro/commit/4d5b1d0a81915607743836324b6943e04e885951 allows for `pcf-pipelines` release to be downloaded from PivNet. 
For Git (local test), the `pcf_pipelines_project_url` parameter in `common/credentials.yml` already allows for it.
For GitHub release, that is the same content as the PivNet release as provided above.
