### ISSUE TITLE
Foundation Name is using default NYC-DEV, even after changing it

### ISSUE THREAD

**Issue by akamalov** [pivotalservices/pcf-pipelines-maestro#28]
Greetings,

Using current version of ```pcf-pipelines-maestro```. Followed the instructions, as well as renamed ```foundations/<foundation-name>.yml``` to match my foundation name. However, no matter it is, it is still deploying to Concourse as ```NYC-DEV```. I looked all over, and cannot find where is it sourcing it from. Please help!

**Comment by z4ce** [comment]
I best guess is that you have a reference to `https://github.com/pivotalservices/pcf-pipelines-maestro` in your common config instead of the new repo you created with your new foundation config

**Comment by akamalov** [comment]
@z4ce  You are absolutely right. Thanks for pointing it out!!
