### ISSUE TITLE
 error applying patch: could not expand pointer: /resources/name=pcf-pipelines

### ISSUE THREAD

**Issue by akamalov** [pivotalservices/pcf-pipelines-maestro#30]
**Environment**

```
Concourse: 3.14.0
pcf-pipelines-maestro: latest
iaas_type: vsphere
cf-pipelines-release-or-tag: v0.23.1
```

Attempting to run ```pipelines/pcf-pipelines-maestro-pivnet.yml```,  however getting the following error:

```
2018-07-03 12:24:48 (8.74 MB/s) - 'fly' saved [16581114/16581114]

FLY version in use:
3.14.0
Performing FLY login to team [main] of Concourse server http://concourse001.XXX.XXXXX.local:8080/
logging in to team 'main'

target saved
Global pipeline patches processing.
Preparing files for all upgrade-ops-manager pipelines
Preparing files for upgrade-tile pipelines
Pre-updates of pcf-pipelines git tag for file [./operations/opsfiles/replace-pcf-pipelines-git-repo-uri.yml].
Applying pcf-pipelines source patch for [git] to upgrade-opsmgr pipelines files.
Patching [./globalPatchFiles/upgrade-ops-manager/aws/pipeline.yml]
2018/07/03 12:24:49 error applying patch: could not expand pointer: /resources/name=pcf-pipelines
```
Any best way to approach this ? Thanks so much!

**Comment by lsilvapvt** [comment]
@akamalov I believe your problem is that you have not updated your `common/credentials.yml` file to use `pcf-pipelines` from `pivnet`, which should be done if you are using `pcf-pipelines-maestro-pivnet.yml` to fly the pipeline:
`pcf-pipelines-source: pivnet`
Once you update that parameter from `git` to `pivnet` and re-run the maestro main pipeline, you should get the team pipelines appropriately generated.

**Comment by akamalov** [comment]
Thank you so much @lsilvapvt for pointing it out. Yes that was the issue. On the other hand, I discovered that a pipeline also looks for ```opsman_uri```, but the configuration was not reflected in foundation template. I had to add it to pass the error:

```
* unbound variable in template: 'opsman_uri'
```
...found in ``` pcf-pipelines-maestro/operations/opsfiles/artifactory/use-product-releases-from-artifactory-tiles.yml:      OPSMAN_URI: {{opsman_uri}}```
