### ISSUE TITLE
Question: Is it possible to automatically accept EULA for pcf-automation from within the pipeline setup?

### ISSUE THREAD

**Issue by akamalov** [pivotalservices/pcf-pipelines-maestro#33]
This is not an issue, just a question.

Question: Is it possible to automatically accept EULA for pcf-automation from within the pipeline setup?

**Comment by lsilvapvt** [comment]
I believe the PivNet API does not allow for EULA automatic acceptance. You can check PivNet's API docs on https://network.pivotal.io/docs/api . Regards.
