### ISSUE TITLE
Create team failing

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotalservices/pcf-pipelines-maestro#9]
CI v: 3.4.1

I am getting the following error when trying to run through the pipeline

    + ./fly -t main set-team -n lab '--basic-auth-username="admin"' '--basic-auth-password="password"'
    Team Name: lab
    Basic Auth: enabled
    GitHub Auth: disabled
    GitLab Auth: disabled
    UAA Auth: disabled
    Generic OAuth: disabled
    could not reach the Concourse server called main:

    inappropriate ioctl for device

    is the targeted Concourse running? better go catch it lol

If I hijack in I can run this command manually with out issue but concourse is asking for a y/n response. I believe this may be hanging the createConcourseFoundationTeam function. 

    root@9cfb959c-6edd-46e8-721a-01eb14b721b6:/tmp/build/780847c5/pcf-pipelines-maestro# ./fly -t 
    main set-team -n lab '--basic-auth-username="admin"' '--basic-auth-password="password"'
    Team Name: lab
    Basic Auth: enabled
    GitHub Auth: disabled
    GitLab Auth: disabled
    UAA Auth: disabled
    Generic OAuth: disabled
    apply configuration? [yN]: error: keyboard interrupt

**Comment by lsilvapvt** [comment]
Thanks for reporting the issue. This problem is due to the fact that the `fly set-team` command changed in Concourse v3.4.1 and it now requires a `--non-interactive` flag for automation scripts. Working on the fix to the maestro scripts for it now. Stay tuned.
